version: '3.7'

services:
  zabbix-postgres:
    image: postgres:alpine
    container_name: zabbix-postgres
    environment:
      POSTGRES_DB: ${ZABBIX_DB_NAME}
      POSTGRES_PASSWORD: ${ZABBIX_DB_PASSWORD}
      POSTGRES_USER: ${ZABBIX_DB_USER}
    networks:
      - zabbix-net
    volumes:
      - /var/lib/zabbix/timezone:/etc/timezone
      - /var/lib/zabbix/localtime:/etc/localtime

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: ${ZABBIX_DB_HOST}
      DB_SERVER_PORT: ${ZABBIX_DB_PORT}
      POSTGRES_DB: ${ZABBIX_DB_NAME}
      POSTGRES_USER: ${ZABBIX_DB_USER}
      POSTGRES_PASSWORD: ${ZABBIX_DB_PASSWORD}
    networks:
      # - zabbix-net
      zabbix-net:
        ipv4_address: 172.25.0.11
    volumes:
      - /var/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /var/lib/zabbix/timezone:/etc/timezone
      - /var/lib/zabbix/localtime:/etc/localtime
    ports:
      - "10051:10051"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: ${ZABBIX_DB_HOST}
      DB_SERVER_PORT: ${ZABBIX_DB_PORT}
      POSTGRES_DB: ${ZABBIX_DB_NAME}
      POSTGRES_USER: ${ZABBIX_DB_USER}
      POSTGRES_PASSWORD: ${ZABBIX_DB_PASSWORD}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: ${ZABBIX_TIMEZONE}
    networks:
      - zabbix-net
    volumes:
      - /var/lib/zabbix/timezone:/etc/timezone
      - /var/lib/zabbix/localtime:/etc/localtime
    ports:
      - "80:8080"
      - "443:8443"

networks:
  zabbix-net:
    ipam:
      config:
        - subnet: 172.25.0.0/16

